### ISSUE TITLE
Keyword color mismatch from original

### ISSUE THREAD

**Issue by handsomefox** [metapho-re/kanagawa-vscode-theme#1]
Big thanks to you for porting all the variants of this theme to VSCode!

Here's the issue:
[The original theme](https://github.com/rebelot/kanagawa.nvim) has different colors for keywords like: `println!` (a macro), `let`, `Ok(())` (expression) and etc. You can see the difference between the [original](https://user-images.githubusercontent.com/36300441/222913073-22b95f11-8c08-4b2b-867c-19072c921de1.png) and the [port](https://raw.githubusercontent.com/metapho-re/kanagawa-vscode-theme/main/assets/wave.png).

Additionally, the other [port](https://github.com/barklan/kanagawa.vscode), from which as far as I know this one was born, actually has what seems to be the correct colors, as seen on this [screenshot](https://raw.githubusercontent.com/barklan/kanagawa.vscode/main/assets/screenshot.png).

Would it be possible to match the original colors? If the theme actually matches everything from the original, it can probably be linked in the original repository under `Extras` with the other ports.

**Comment by paccodes** [comment]
@handsomefox Thank you for providing feedback!
I updated some of the colors to better match the Neovim theme, based on the rust example used in the assets.
It's not a perfect match yet, and I wonder if it can ever become one since the semantic parsing in VSCode seems to give slightly different results.
But it should be much closer now. Please take a look.

**Comment by handsomefox** [comment]
Yes, the current result is way closer, there are some minor differences, but overall I think it's good, IMHO it's even better than the other VSCode port now, when comparing Rust at least.

Here's one example of a little detail mismatching:
1 (println):
VSCode: 
![VSCode](https://user-images.githubusercontent.com/29275085/236264921-c94ad0dd-6ff9-4cff-8b0c-07c1cb798a6f.png)
Original: 
![Original](https://user-images.githubusercontent.com/29275085/236264950-7bd85f9f-b2f8-4737-bc0a-2b5f1cc2d54a.png)
2 (braces):
VSCode: 
![VSCode](https://user-images.githubusercontent.com/29275085/236265796-4c616596-0f03-4a7a-ab7a-177097d616e0.png)
Original: 
![Original](https://user-images.githubusercontent.com/29275085/236265848-bb6cb313-aa07-4a38-932f-5c33c531ccdb.png)

I'm not even sure if this requires a fix, or as you've already said, is even fixable, but whatever, seems ok the way it is.
