### ISSUE TITLE
Request to add to Open VSX

### ISSUE THREAD

**Issue by Saladin1812** [metapho-re/kanagawa-vscode-theme#3]
Hi there, Really like the ports however I wish you can put the extension on https://open-vsx.org/ So people on [VS Codium](https://vscodium.com/) and on open source Code OSS can use the theme easily. Publishing on open vsx is easy.

**Comment by paccodes** [comment]
Hey there.
Thanks for your feedback!
I published it here: [https://open-vsx.org/extension/metaphore/kanagawa-vscode-color-theme](https://open-vsx.org/extension/metaphore/kanagawa-vscode-color-theme)

**Comment by Saladin1812** [comment]
Perfect thanks :+1:
