### ISSUE TITLE
The cursor color in vim is covered rather than inverted.

### ISSUE THREAD

**Issue by yifan0414** [metapho-re/kanagawa-vscode-theme#4]
![image](https://github.com/metapho-re/kanagawa-vscode-theme/assets/45898625/ecd4b133-16fa-4212-b2f3-933867fce1ec)

**Comment by paccodes** [comment]
Thanks for catching this @yifan0414.
I published a new version 0.3.0.
Please upgrade and let me know what you think.

**Comment by yifan0414** [comment]
awesome!
