### ISSUE TITLE
Improper highlighting in JSX

### ISSUE THREAD

**Issue by sahmed007** [metapho-re/kanagawa-vscode-theme#5]
The `className` and non-React components like a `div` are the same colors which make it hard to scan code. It would be great if these could be separate colors.
![Screenshot 2024-07-01 at 14 39 47](https://github.com/metapho-re/kanagawa-vscode-theme/assets/12787871/18bf5736-ace4-4aec-aa6c-320d61478829)

**Comment by paccodes** [comment]
Hi @sahmed007,

Thank you for your feedback.
What about something like this?

![sample](https://github.com/metapho-re/kanagawa-vscode-theme/assets/49805430/0f3f5dcb-8b9a-48d9-92db-b6b6e46b939c)

**Comment by paccodes** [comment]
@sahmed007 I published a new version. Please check.

**Comment by sahmed007** [comment]
Looks great!
